### ISSUE TITLE
Applying policy on tables

### ISSUE THREAD

**Issue by belalaboabdo** [entechlog/dbt-snow-mask#65]
We currently have `dbt_snow_mask` configured in our `dbt_project.yml` to create masking policies for all models on run start and apply policies to run as a post-hook. When materializing a model as a table that references columns from an upstream model with a masking policy applied to it we get the following database error.

```
String '357715109e6a2d0c23343a5dda82be162326e4715ec69bb8f24755848739d910' is too long and would be truncated
```

dbt_project.yml
```
on-run-start:
  - "{{ dbt_snow_mask.create_masking_policy('models')}}"

vars:
  use_common_masking_policy_schema_only: "True"
  common_masking_policy_schema: "PUBLIC"

models:
  +post-hook:
    - "{{ dbt_snow_mask.apply_masking_policy('models') }}"
```
