### ISSUE TITLE
dbt-snow-mask does not appear to honor `quote: true`

### ISSUE THREAD

**Issue by jmkacz** [entechlog/dbt-snow-mask#80]
Does dbt-snow-mask honor the `quote` config (https://docs.getdbt.com/reference/resource-properties/quote) on at least the column?

I have collected the following information from one of our Analytics Engineers.

Situation:
* We have no control over table or column naming upstream of the data warehouse.
* The ETL system we use creates the tables in our data warehouse as they appear upstream.
* There is an upstream database which uses periods in their column names.

`models/_foo_source.yml`

```
version: 2
sources:
  - name: foo
    database: "RAW" 
    schema: foo
    tables:
      - name: bar
        columns:
          - name: CONFIG.IDS.ORG.INSTITUTIONS.MANUALCONFIG
            quote: true
            meta:
              masking_policy: masking_policy_123
```

When we run dbt-snow-mask on the sources, we see the following error:

```
SQL compilation error:
syntax error line 2 at position 52 unexpected '.'.
```

Here is the query it attempted to run:

```
alter table RAW.foo.bar
                                modify column CONFIG.IDS.ORG.INSTITUTIONS.MANUALCONFIG
                                set masking policy  RAW.PUBLIC.masking_policy_123   force
/* {"app": "dbt", "dbt_snowflake_query_tags_version": "2.5.0", "dbt_version": "2024.12.12+0367206", "project_name": "dbt_amplify", "target_name": "PROD", "target_database": "TRANSFORMED", "target_schema": "_", "invocation_id": "85d61dd6-7f0c-4ed6-8b56-9c6307ed8819", "run_started_at": "2024-12-17T20:00:21.383722+00:00", "full_refresh": false, "which": "build", "dbt_cloud_project_id": "188744", "dbt_cloud_job_id": "262756", "dbt_cloud_run_id": "352734327", "dbt_cloud_run_reason_category": "scheduled", "dbt_cloud_run_reason": "scheduled"} */
```

We see the column name is not quoted.

Looking at the source code, it seems plausible that quoting is not honored. Though, that might be abstracted behind a function I am not seeing at the moment.

https://github.com/entechlog/dbt-snow-mask/blob/main/macros/snow-mask/apply-policy/apply_masking_policy_list_for_sources.sql#L66

I've traced the logic back to:
* https://github.com/entechlog/dbt-snow-mask/blob/main/macros/snow-mask/apply-policy/apply_masking_policy_list_for_sources.sql#L21
* https://github.com/entechlog/dbt-snow-mask/blob/fc59b0c5e31c2364921b58fc90f60c36808aa5ee/macros/snow-mask/get_meta_objects.sql#L6
* ... I paused here ...

Here is what I pulled out of the manifest.json file:

```
jq '.sources."source.dbt_amplify.foo.bar".columns."CONFIG.IDS.ORG.INSTITUTIONS.MANUALCONFIG"' manifest.json
```

```
{
  "name": "CONFIG.IDS.ORG.INSTITUTIONS.MANUALCONFIG",
  "meta": {
    "masking_policy": "masking_policy_123"
  },
  "data_type": null,
  "constraints": [],
  "quote": true,
  "tags": [],
  "granularity": null
}
```

**Comment by rubyDoomsday** [comment]
I am also hitting this issue and can provide the following context. 

```
# props.yaml
version: 2
models:
- name: SOME_MODEL
  columns:
  - name: First Name
    description: ''
    quote: true
    meta:
      masking_policy: mp_pii_string

```

Results in a build failure error:

```
18:17:08  14:17:08 | applying masking policy to model  : GOVERNANCE.MASKING_POLICIES.MP_PII_STRING on workspace.ws.SOME_MODEL.First Name [force = True]
18:17:08  1 of 1 ERROR creating sql view model ws.SOME_MODEL  [ERROR in 4.45s]
18:17:08
18:17:12    Database Error in model SOME_MODEL (models/SOME_MODEL.sql)
  001003 (42000): SQL compilation error:
  syntax error line 2 at position 48 unexpected 'Name'.
  compiled code at target/run/project/models/SOME_MODEL.sql
18:17:12
18:17:12  Done. PASS=1 WARN=0 ERROR=1 SKIP=1 TOTAL=3

```

As a result I have no way to apply masking policies to these models.
